package com.verde.pistache.model;
// Generated 20/06/2018 04:36:58 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="verdepistache"
)
public class Producto  implements java.io.Serializable {


     private Integer idproducto;
     private String codigo;
     private String descripcion;
     private String talla;

    public Producto() {
    }

    public Producto(String codigo, String descripcion, String talla) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.talla = talla;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idproducto", unique=true, nullable=false)
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }

    
    @Column(name="codigo", length=45)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="talla", length=45)
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }




}


