package com.verde.pistache.model;
// Generated 28/06/2018 05:51:43 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.AssertTrue;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users",
        uniqueConstraints = @UniqueConstraint(columnNames = "correo")
)

public class Users implements java.io.Serializable {

    @Override
    public String toString() {
        return "Users{" + "iduser=" + iduser + ", username=" + username + ", correo=" + correo + ", telefono=" + telefono + ", password=" + password + ", cp=" + cp + ", ciudad=" + ciudad + ", direccion=" + direccion + ", apellidos=" + apellidos + '}';
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "iduser", unique = true, nullable = false)
    private Integer iduser;
    @Column(name = "username", length = 45)
    @NotEmpty(message = "Este campo no puede ser vacio")
    private String username;
    
    
    @Column(name = "correo", unique = true, length = 45)
    @NotEmpty(message = "Este campo no puede ser vacio")
    @Email(message = "Correo  no valido")
    private String correo;
    @Column(name = "telefono", length = 45)
    @NotEmpty(message = "Este campo no puede ser vacio")

    private String telefono;
    
    @Size(min=6, max=30)
    @Column(name = "password", length = 45)
    @NotEmpty(message = "Este campo no puede ser vacio")
    private String password;
    @Column(name = "cp", length = 45)
    @NotEmpty(message = "Este campo no puede ser vacio")
    private String cp;
    @Column(name = "ciudad", length = 45)
    @NotEmpty(message = "Este campo no puede ser vacio")
    private String ciudad;
    @Column(name = "direccion", length = 200)
    @NotEmpty(message = "Este campo no puede ser vacio")
    private String direccion;
    @Column(name = "apellidos", length = 45)
    @NotEmpty(message = "Este campo no puede ser vacio")
    private String apellidos;
    // @Equals(property="password")
    
    
    
    @Transient
    private String passwordConfirm;

   

    public String getPasswordConfirm() {
        return passwordConfirm;
    }

    public void setPasswordConfirm(String passwordConfirm) {
        this.passwordConfirm = passwordConfirm;
    }

    public Users() {
    }

    public Users(String username, String correo, String telefono, String password, String cp, String ciudad, String direccion, String apellidos) {
        this.username = username;
        this.correo = correo;
        this.telefono = telefono;
        this.password = password;
        this.cp = cp;
        this.ciudad = ciudad;
        this.direccion = direccion;
        this.apellidos = apellidos;
    }

    public Integer getIduser() {
        return this.iduser;
    }

    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCp() {
        return this.cp;
    }

    public void setCp(String cp) {
        this.cp = cp;
    }

    public String getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

}
